// Generated by https://quicktype.io

export interface TechnicalSheetVisibility {
    decision:               { [key: string]: Visibility };
    privateConditions:      { [key: string]: Visibility };
    operationParticipants:  { [key: string]: Visibility };
    otherConditions:        { [key: string]: Visibility };
    decisionRules:          { [key: string]: Visibility };
    contractualInformation: { [key: string]: Visibility };
    operationalReport:      { [key: string]: Visibility };
}

export interface Visibility {
    readOnly: boolean;
    visible:  boolean;
}
