// Generated by https://quicktype.io

export interface Task {
    taskId:                   string;
    viewModeActions:          string[];
    editModeActions:          string[];
    mainActions:              string[];
    operationNumber:          null;
    processName:              string;
    productCode:              string;
    productFamilyCode:        string;
    assigneeUsername:         null;
    locked:                   boolean;
    lastDecisionScaleDecisor: boolean;
}
